### ISSUE TITLE
Region of Interest (ROI) metadata

### ISSUE THREAD

**Issue by cpaniaguam** [WilhelmusLab/IceFloeTracker.jl#192]
Should the region of interest be metadata to be collected by the command line interface?

In 
https://github.com/WilhelmusLab/ice-floe-tracker/blob/0076a08836b2de271f254bd2a6e3cc852acaf5f1/existing_code/final_2020.m#L301-L327 the land mask is cropped to some hard coded specs. 

Should the pipeline assume the the images are going to be cropped to the correct size? If not, what should the correct format for this metadata be?

@mkkim400 @danielmwatkins @mmwilhelmus @mirestrepo @tdivoll

**Comment by danielmwatkins** [comment]
I like the way that the landmask and satellite image are downloaded having the exact same dimensions as each other in the current code. It looks to me like the portion of code that you highlighted is where the image is cut into three pieces, which is not something we want to exactly recreate.
