### ISSUE TITLE
Post-process floes

### ISSUE THREAD

**Issue by cpaniaguam** [WilhelmusLab/IceFloeTracker.jl#208]
There is a post-processing routine after features are extracted from the segmented images, apparently for visualization purposes only.

https://github.com/WilhelmusLab/ice-floe-tracker/blob/0076a08836b2de271f254bd2a6e3cc852acaf5f1/existing_code/final_2020.m#L1541

```matlab
im= imcrop(BW_new,prop(t,10:13));
outline = bwperim(im);
%figure, imshow(outline)

im_fill= imfill(outline,'holes');
%figure, imshow(im_fill)

im_fill2 = bwareaopen(im_fill, 50);
%figure, imshow(im_fill2)

floe = bwareafilt(im_fill2, 1, 'largest'); % keeps biggest floe in image
%figure, imshow(floe)

%only contours
floe2 =bwperim(floe);
floe3 = imdilate(floe2, true(2));

notzeros = find(floe==1);

new = zeros(size(BW_new));
Y1=prop(t,11);   
Y2=prop(t,11)+prop(t,13);
X1=prop(t,10);
X2=prop(t,10)+prop(t,12);

    if Y2>p
       Y2=p;
    else 
    end

    if X2>q
       X2=q;
    else
    end

new=zeros(p,q);    
new(Y1:Y2, X1:X2) = floe;

new1=zeros(p,q);  
new1(Y1:Y2, X1:X2) = floe3;

%plot on coast image
notzeros2 = find(new1==1);


image1(notzeros2)=0; %if =1 it will draw ice floe, if =0 it will delete it
image2(notzeros2)=0; %if =1 it will draw ice floe, if =0 it will delete it
image3(notzeros2)=0; %if =1 it will draw ice floe, if =0 it will delete it
```

**Comment by danielmwatkins** [comment]
I don't think we need to include this specific post-processing routine. Post-processing is important though, and I have some methods I've been testing that so far seem to be working well for removing false positives.

**Comment by cpaniaguam** [comment]
> I don't think we need to include this specific post-processing routine. Post-processing is important though, and I have some methods I've been testing that so far seem to be working well for removing false positives.

In view of this, we'll close this issue.
