### ISSUE TITLE
Make func to convert floe centroid to geo coordinates

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/IceFloeTracker.jl#279]
Add a util function to use the local pixel coordinates in the `floe_props` output and convert to geographic coordinates
* likely need these in polar stereographic (epsg=EPSG3413)
* some Python code from @ellenbuckley:

`f = interpolate.interp1d(np.arange(0,len(x1_region[‘x1_region’][0])),x1_region[‘x1_region’])` <br/>
`#the fifth column Centroid (1) of the 99th day that the IFT is run on is the x pixel location`  <br/>
`x_new = [a[5] for a in prop[‘properties’][0][99]]` <br/>
`#convert the centroid values from pixel location to polar sterographic coordinates indicated in x1_region`  <br/>
`x2 = f(x_new)`  <br/>
`f = interpolate.interp1d(np.arange(0,len(y1_region[‘y1_region’][0])),y1_region[‘y1_region’])`  <br/>
`#the sixth column Centroid (2) of the 99th day that the IFT is run on is the y pixel location`  <br/>
`y_new = [a[6] for a in prop[‘properties’][0][99]]`  <br/>
`y2 = f(y_new)` 

The above code is based on the Matlab version of IceFloeTracker, thus, look at the regionprops output from Matlab to see what `x1_region` and `y1_region` contain

**Comment by cpaniaguam** [comment]
> The above code is based on the Matlab version of IceFloeTracker, thus, look at the regionprops output from Matlab to see what `x1_region` and `y1_region` contain

@danielmwatkins @ellenbuckley @tdivoll 
Does anyone know which set of lines in the Matlab script do this work? Maybe I can look into it a bit deeper.
https://github.com/WilhelmusLab/ice-floe-tracker-pipeline/pull/29

**Comment by ellenbuckley** [comment]
I think the new code that Daniel sent is independent of the matlab code
right? That was an old workaround I used but I think we shouldn't have to
use that x1region and y1region

**Comment by danielmwatkins** [comment]
Right, I didn't reference the Matlab code in the code snippet I provided.
