### ISSUE TITLE
Translate alt morphological segmentation routine

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/IceFloeTracker.jl#327]
Convert @ellenbuckley's new segmentation routine from Python to Julia
Use the name `FSD segmentation` for floe size distribution
*  The alternate functions will replace some of the preprocessing steps as well as some of the segmentation steps
*  May then need to update the ice-floe-tracker-pipeline CLI to toggle standard and alt segmentation routines

**Comment by cpaniaguam** [comment]
@tdivoll @ellenbuckley Is that code in a repo?

**Comment by cpaniaguam** [comment]
IFT now has functionality in python, so translating an alternative preprocessing routine is not really needed. Instead it'd need incorporation into IFT's code base.

**Comment by mirestrepo** [comment]
Python pacake done https://github.com/WilhelmusLab/eb-seg-sandbox

Translation to Julia may not be necessary
