### ISSUE TITLE
Collision resolving breaking if too many collisions shared

### ISSUE THREAD

**Issue by cpaniaguam** [WilhelmusLab/IceFloeTracker.jl#353]
https://github.com/WilhelmusLab/IceFloeTracker.jl/blob/290d7bdbd691f83f5fecca19b7a2d6ad8719eb0b/src/tracker/tracker-funcs.jl#L443

When floes share several potential matching floes, the collision resolution routine drops rows that later are looked up by row index which throws an out of bounds error when checking goodness of fit for floes having dropped floes in its set of potential matches.

**Comment by tdivoll** [comment]
Can you create a unique ID based on index and floe ID and then do the lookup using the unique ID, but still drop rows by only index when needed?

**Comment by cpaniaguam** [comment]
I like that idea. A function could be created to drop by floe ID in a safer way than  by row index.
