### ISSUE TITLE
Delete or move to IFTPipeline readme

### ISSUE THREAD

**Issue by cpaniaguam** [WilhelmusLab/IceFloeTracker.jl#359]
There are sections discussing fetchdata, the cli, and some old stuff about snakemake in the readme. I think parts of this could be moved to the IFTPipeline repo and the remaining deleted altogether.

https://github.com/WilhelmusLab/IceFloeTracker.jl/blob/ce9869e0f07caeec944d6e67e9b35840f01ce668/README.md?plain=1#L72-L104

**Comment by tdivoll** [comment]
Closed by #360
