### ISSUE TITLE
Tracker expects column names that are not present in all cases

### ISSUE THREAD

**Issue by danielmwatkins** [WilhelmusLab/IceFloeTracker.jl#362]
The tracker expects the columns "latitude" and "longitude", which are not present if there is a data frame with 0 rows. We should add something that expands the empty data frame to have the expected rows.

The place where I expect the change needs to be made is close to line 533 in `tracker-funcs`, where columns are dropped from the props table. The lat/lon columns are added after that if/then clause.

**Comment by cpaniaguam** [comment]
@danielmwatkins Have you been able to verify whether the patch in #363 fixed this bug?

**Comment by danielmwatkins** [comment]
Yes, the fix worked.
