### ISSUE TITLE
Landmask bleeding into labeled image

### ISSUE THREAD

**Issue by danielmwatkins** [WilhelmusLab/IceFloeTracker.jl#414]
There's an issue where sometimes the labeled image appears to mainly be the landmask. This has shown up in a handful of cases, I'm showing two images from a recent run on a 1400 km by 1400 km case from the Barents Sea. In one image, you can see the expected result with no labels on land and some pretty reasonable looking detected floes. In the other, the island has been labeled as a floe. I suspect at some point a binary mask is getting flipped, but I'm not sure where that could be happening. 

![20240325_aqua](https://github.com/WilhelmusLab/IceFloeTracker.jl/assets/8204369/0c566b20-ba65-48fd-9d3d-e8c1546ceee6)
![20240321_terra](https://github.com/WilhelmusLab/IceFloeTracker.jl/assets/8204369/c0b1258d-ddf5-4759-a3b7-147cb5ca51df)

**Comment by danielmwatkins** [comment]
It looks like the issue is appearing in the k-means section of Segmentation F. I suspect there's an issue with the ice labels, and will look into whether the remove_landmask functionality is working correctly.
[Identifying causes of error in Segmentation F.pdf](https://github.com/user-attachments/files/17316746/Identifying.causes.of.error.in.Segmentation.F.pdf)

**Comment by cpaniaguam** [comment]
@danielmwatkins I think this is now fixed, right?

**Comment by danielmwatkins** [comment]
Yes, addressed in the ice-floe-tracker-pipeline
