### ISSUE TITLE
Test latlon.py

### ISSUE THREAD

**Issue by danielmwatkins** [WilhelmusLab/IceFloeTracker.jl#468]
Output of latlon.py is used in a few tests already. However we should have a test of get_latlon specifically, so that when we replace latlon.py with latlon.jl, we know that it is still doing the same thing. I've already made a pull request with some data to use for testing, we just need a simple test to see that the latitude/longitude is coming back within a reasonable tolerance.

**Comment by cpaniaguam** [comment]
Completed in #467
